# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNAppCenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNAppCenter

  target 'RNAppCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNAppCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNAppCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNAppCenter-tvOS

  target 'RNAppCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
